<?php

namespace app\admin\controller;

use think\Controller;

class Link extends Common {
    protected $db;
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->db=new \app\common\model\Link();
    }

    /*
     * 友链首页
     */
    public function index(){
        $data=db('link')->select();
        $this->assign('data',$data);
        return $this->fetch();
    }

    /*
     * 友链添加
     */
    public function store(){
        if(request()->isPost()){
            $res=$this->db->store(input('post.'));
            if($res['valid']){
                $this->success($res['msg'],'index');
            }else{
                $this->error($res['msg']);
            }
        }
        return $this->fetch();
    }

    /*
     * 友链编辑
     */
    public function edit(){
        if(request()->isPost()){
            $res=$this->db->edit(input('post.'));
            if($res['valid']){
                $this->success($res['msg'],'index');
            }else{
                $this->error($res['msg']);
            }
        }
        $id=input('param.id');
        //halt($id);
        $oldData=db('link')->where('id',$id)->find();
        //halt($oldData);
        $this->assign('oldData',$oldData);
        return $this->fetch();
    }

    /*
     * 删除友链
     */
    public function del(){
        $res=$this->db->del(input('get.id'));
        if($res['valid']){

            //删除成功，跳转列表页
          $this->success($res['msg'],'index');
        }else{
            //删除失败
            $this->error($res['msg']);
        }
    }
}
