<?php

namespace app\index\controller;

use app\common\model\User;
use think\Controller;
use think\Request;
class Reg extends Controller{
    protected $db;
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->db=new \app\common\model\User();
    }
    /*
     * 发送邮件
     */
    public function sendcaptcha(){
        //p($_POST['email']);
        $mail=new Mail();
        //随机验证码，加密微秒数，从第一个字符开始截取，截取4位
        $captcha=substr(md5(microtime(true)),0,4);
        //把用户的邮箱，给用户发送的验证码，和当前发送验证码的时间存储到session中，
        //用来注册的时候的验证
        session('captcha',$captcha);
        session('email',input('post.email'));
        session('savetime',time());
        $res=$mail->send(input('post.email'),'欢迎您注册“技术博客”网站，您注册验证码是：'.$captcha.'，5分钟后验证码失效，千万不能泄露！');
        if($res){
            //发送成功
            echo json_encode(['errorno'=>1,'errormsg'=>'ok']);
        }else{
            //发送失败
            echo json_encode(['errorno'=>0,'errormsg'=>'请联系管理员 发送信息到“linran136@163.com”']);
        }
    }

    /*
     * 注册账号
     */
    public function reg(){
        //51dd
        if(request()->isPost()){
            $res=$this->db->reg(input('post.'));
            if($res['valid']){
                //跳转到登录页面
                $this->success($res['msg'],'index/login/login');
            }else{
                $this->error($res['msg']);
            }
        }
        return $this->fetch();
    }
}
